FROM ft-rails:on-build

EXPOSE 3000
CMD [ "rails" , "s", "-b", "0.0.0.0", "-p", "3000"]

# build:
# docker build -t ex02 .

# run:
# docker run -it --rm -p 3000:3000 ex02

# http://192.168.99.103:3000